### ISSUE TITLE
希望改进一个功能

### ISSUE THREAD

**Issue by cacacainchina** [tctianchi/War3Trainer#6]
这个修改器非常好用，但是有一个缺点。就是当修改出来的物品是带主动技能的时候，那么技能是无法使用的。比如飓风权杖是带吹风技能的，那么修改出来的权杖点击是没用的。同样的情况出现在修改出来的红瓶和蓝瓶上。还有比如出现在属性书上，等等。不知道怎么解决？

**Comment by tctianchi** [comment]
扔在地上再捡起来也不行吗？
