### ISSUE TITLE
发现倒卖的人

### ISSUE THREAD

**Issue by lighterEB** [tctianchi/War3Trainer#7]
QQ群490668914和这个群主，这个人用你的进行倒卖

**Comment by tctianchi** [comment]
这个库所使用的MIT授权协议，对于二次售卖没有特别的限制。不过在issue中贴QQ或许有广告效果也说不定呢 :see_no_evil:

**Comment by lighterEB** [comment]
> 
> 
> 这个库所使用的MIT授权协议，对于二次售卖没有特别的限制。不过在issue中贴QQ或许有广告效果也说不定呢 🙈

额，你这样说也确实好像有广告嫌疑，那我删除号码
